### ISSUE TITLE
wrong XLM deposit to [Tempo]GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S

### ISSUE THREAD

**Issue by gCube** [tempofr/stellar#11]
Hi There,

I have tried to contact Tempo in France and on LinkedIN, sadly enough no reply nor any english speaking employee.
There is a wrong deposit on the wallet Tempo, i would like to ask kindly to revert this transaction.

https://stellar.expert/explorer/public/tx/360f518b61de31bd83902202875709a5b61c39cbdd5637dcca8cd2077cb1b363
![Capture](https://user-images.githubusercontent.com/65534746/104650014-df476700-56b5-11eb-95c1-422372fc4a1b.PNG)

Greetings,
Cube

**Comment by antb123** [comment]
Hi email support@tempo.eu.com normally for support issues.

You sent to the issuing wallet not the receiving wallet... and it looks
like you send XLM not EURT?

Yours

**Comment by gCube** [comment]
Thanks for getting back to me so quickly.

Indeed, i have sent XLM to issuing wallet. Which was generated by GA3FJQY26BBAADIGIMSJSJ5QB2VYDIFVXZMYVFVARR7B43A2QDQS3GBJ. I tried contacting on Email and on the Website with no luck.

I have pasted the TX which obviously is not EURT 360f518b61de31bd83902202875709a5b61c39cbdd5637dcca8cd2077cb1b363.

As this is a large portion of my portfolio please understand my concern as this is taking quite long.

Thanks for understanding.

I'm kindly asking for the return of the assets (XLM 905.2503) to the source of the transaction.

**Comment by antb123** [comment]
I don't work for Tempo anymore

And there are many scammers who try to take funds - I will send it over
shortly

**Comment by gCube** [comment]
I understand, nor do i want to place any wallet address out here.
This was simply a mistake from my side and i sincerely apologize for all of this.

Thank you for your time.

**Comment by gCube** [comment]
Hi there, any chance on returning the funds to the source wallet?

**Comment by gCube** [comment]
I have received my funds! Thank you very much, i can't stress this enough.

<3
